
export default {
  FEATURE_BOOKMAR_BAR_SET: 'FEATURE_BOOKMAR_BAR_SET',
  WALLPAPER_TRANSITION_SHOW_DURATION_SET: 'WALLPAPER_TRANSITION_SHOW_DURATION_SET',
  WALLPAPER_UPDATE_FREQUENCY_SET: 'WALLPAPER_UPDATE_FREQUENCY_SET'
}
